const membersData = [
    {
      id: 1,
      name: "Aarushi Lodha",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/aarushi-lodha-8a8483324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 2,
      name: "Aayushi M.",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/ayushi-maheshwari-372a532a0?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 3,
      name: "Anshul",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/anshul-vijayvergiya-90a857267/",
    },
    {
      id: 4,
      name: "Khushali Acharya",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/khushali-acharya-621865293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 5,
      name: "Mudit Paliwal",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/mudit-paliwal-108739277/",
    },
    {
      id: 6,
      name: "Parul Sharma",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/parul-sharma-b360862a1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 7,
      name: "Purvik Sharma",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/in/purviksharma/",
    },
    {
      id: 8,
      name: "Raj Gehlot",
      role: "Developer",
      year: 2025,
      linkedin: "https://www.linkedin.com/",
    },
    {
      id: 9,
      name: "Tanishq S.",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/tanishq-saini-316b85277/",
    },
    {
      id: 10,
      name: "Tanshi",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/tanshi-09164032a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 11,
      name: "Teesha Garg",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/teesha-garg-811b39293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 12,
      name: "Vandna Gour",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/vandana-gour-a53ab9303/",
    },
    {
      id: 13,
      name: "Vanisha Sharma",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/vanisha-sharma-102450296?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 14,
      name: "Vishnu Singh",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/vishnu-singh-4741002a9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      id: 15,
      name: "Yash Goyal",
      role: "Developer",
      year: 2026,
      linkedin: "https://www.linkedin.com/in/yash-goyal-1a67722a4/",
    },
    {
      id: 16,
      name: "Yashika Kansal",
      role: "Developer",
      year: 2026,
      linkedin: "www.linkedin.com/in/yashika-kansal-120a462a8",
    },
    {
      id: 17,
      name: "Yashpal Bhati",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/in/yashpal-bhati-028064294/",
    },
    {
      id: 18,
      name: "Anushka Poddar",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/in/",
    },
    {
      id: 19,
      name: "Lokesh Prajapat",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/in/lokesh-prajapat-354756279/",
    },
    {
      id: 20,
      name: "Meet Sharma",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/in/meet-sharma-45ba60291",
    },
    {
      id: 21,
      name: "Prince",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/",
    },
    {
      id: 22,
      name: "Shreepal Singh",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/",
    },
    {
      id: 23,
      name: "Sumit Chahar",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/in/",
    },
    {
      id: 24,
      name: "Harshit Sharma",
      role: "Developer",
      year: 2027,
      linkedin: "https://www.linkedin.com/in/harshit-sharma-959065281/",
    },

  ];
  
  export default membersData;
